import { request } from "http"



let wordArr =[
    {
        type:'1',word:'the',
        imgUrl:require('../../assets/word/0001.png'),
    },
    {
        type:'1',word:'be',
        imgUrl:require('../../assets/word/0002.png'),
    },{
        type:'1',type:'1',word:'and',
        imgUrl:require('../../assets/word/0003.png'),
    },{
        type:'1',word:'of',
        imgUrl:require('../../assets/word/0004.png'),
    },{
        type:'1',word:'a',
        imgUrl:require('../../assets/word/0005.png'),
    },{
        type:'1',word:'in',
        imgUrl:require('../../assets/word/0006.png'),
    },{
        type:'1',word:'to',
        imgUrl:require('../../assets/word/0007.png'),
    },{
        type:'1',word:'have',
        imgUrl:require('../../assets/word/0008.png'),
    },{
        type:'1',word:'it',
        imgUrl:require('../../assets/word/0009.png'),
    },{
        type:'1',word:'i',
        imgUrl:require('../../assets/word/0010.png'),
    },{
        type:'1',word:'that',
        imgUrl:require('../../assets/word/0011.png'),
    },{
        type:'1',word:'for',
        imgUrl:require('../../assets/word/0012.png'),
    },{
        type:'1',word:'you',
        imgUrl:require('../../assets/word/0013.png'),
    },{
        type:'1',word:'he',
        imgUrl:require('../../assets/word/0014.png'),
    },{
        type:'1',word:'with',
        imgUrl:require('../../assets/word/0015.png'),
    },{
        type:'1',word:'on',
        imgUrl:require('../../assets/word/0016.png'),
    },{
        type:'1',word:'do',
        imgUrl:require('../../assets/word/0017.png'),
    },{
        type:'1',word:'say',
        imgUrl:require('../../assets/word/0018.png'),
    },{
        type:'1',word:'this',
        imgUrl:require('../../assets/word/0019.png'),
    },{
        type:'1',word:'they',
        imgUrl:require('../../assets/word/0020.png'),
    },{
        type:'1',word:'at',
        imgUrl:require('../../assets/word/0021.png'),
    },{
        type:'1',word:'but',
        imgUrl:require('../../assets/word/0022.png'),
    },{
        type:'1',word:'we',
        imgUrl:require('../../assets/word/0023.png'),
    },{
        type:'1',word:'his',
        imgUrl:require('../../assets/word/0024.png'),
    },{
        type:'1',word:'from',
        imgUrl:require('../../assets/word/0025.png'),
    },{
        type:'1',word:'not',
        imgUrl:require('../../assets/word/0026.png'),
    },{
        type:'1',word:'by',
        imgUrl:require('../../assets/word/0027.png'),
    },{
        type:'1',word:'she',
        imgUrl:require('../../assets/word/0028.png'),
    },{
        type:'1',word:'or',
        imgUrl:require('../../assets/word/0029.png'),
    },{
        type:'1',word:'as',
        imgUrl:require('../../assets/word/0030.png'),
    },{
        type:'1',word:'what',
        imgUrl:require('../../assets/word/0031.png'),
    },{
        type:'1',word:'go',
        imgUrl:require('../../assets/word/0032.png'),
    },{
        type:'1',word:'their',
        imgUrl:require('../../assets/word/0033.png'),
    },{
        type:'1',word:"can",
        imgUrl:require('../../assets/word/0034.png'),
    },{
        type:'1',word:'who',
        imgUrl:require('../../assets/word/0035.png'),
    },{
        type:'1',word:'get',
        imgUrl:require('../../assets/word/0036.png'),
    },{
        type:'1',word:'if',
        imgUrl:require('../../assets/word/0037.png'),
    },{
        type:'1',word:'would',
        imgUrl:require('../../assets/word/0038.png'),
    },{
        type:'1',word:'her',
        imgUrl:require('../../assets/word/0039.png'),
    },{
        type:'1',word:'all',
        imgUrl:require('../../assets/word/0040.png'),
    },{
        type:'1',word:'my',
        imgUrl:require('../../assets/word/0041.png'),
    },{
        type:'1',word:'make',
        imgUrl:require('../../assets/word/0042.png'),
    },{
        type:'1',word:'about',
        imgUrl:require('../../assets/word/0043.png'),
    },{
        type:'1',word:'konw',
        imgUrl:require('../../assets/word/0044.png'),
    },{
        type:'1',word:'will',
        imgUrl:require('../../assets/word/0045.png'),
    },{
        type:'1',word:'up',
        imgUrl:require('../../assets/word/0046.png'),
    },{
        type:'1',word:'one',
        imgUrl:require('../../assets/word/0047.png'),
    },{
        type:'1',word:'time',
        imgUrl:require('../../assets/word/0048.png'),
    },{
        type:'1',word:'there',
        imgUrl:require('../../assets/word/0049.png'),
    },{
        type:'1',word:'year',
        imgUrl:require('../../assets/word/0050.png'),
    },{
        type:'1',word:'so',
        imgUrl:require('../../assets/word/0051.png'),
    },{
        type:'1',word:'think',
        imgUrl:require('../../assets/word/0052.png'),
    },{
        type:'1',word:'when',
        imgUrl:require('../../assets/word/0053.png'),
    },{
        type:'1',word:'which',
        imgUrl:require('../../assets/word/0054.png'),
    },{
        type:'1',word:'them',
        imgUrl:require('../../assets/word/0055.png'),
    },{
        type:'1',word:'some',
        imgUrl:require('../../assets/word/0056.png'),
    },{
        type:'1',word:'me',
        imgUrl:require('../../assets/word/0057.png'),
    },{
        type:'1',word:'people',
        imgUrl:require('../../assets/word/0058.png'),
    },{
        type:'1',word:'take',
        imgUrl:require('../../assets/word/0059.png'),
    },{
        type:'1',word:'out',
        imgUrl:require('../../assets/word/0060.png'),
    },{
        type:'1',word:'into',
        imgUrl:require('../../assets/word/0061.png'),
    },{
        type:'1',word:'just',
        imgUrl:require('../../assets/word/0062.png'),
    },{
        type:'1',word:'see',
        imgUrl:require('../../assets/word/0063.png'),
    },{
        type:'1',word:'him',
        imgUrl:require('../../assets/word/0064.png'),
    },{
        type:'1',word:'your',
        imgUrl:require('../../assets/word/0065.png'),
    },{
        type:'1',word:'come',
        imgUrl:require('../../assets/word/0066.png'),
    },{
        type:'1',word:'could',
        imgUrl:require('../../assets/word/0067.png'),
    },{
        type:'1',word:'now',
        imgUrl:require('../../assets/word/0068.png'),
    },{
        type:'1',word:'than',
        imgUrl:require('../../assets/word/0069.png'),
    },{
        type:'1',word:'like',
        imgUrl:require('../../assets/word/0070.png'),
    },{
        type:'1',word:'other',
        imgUrl:require('../../assets/word/0071.png'),
    },{
        type:'1',word:'how',
        imgUrl:require('../../assets/word/0072.png'),
    },{
        type:'1',word:'then',
        imgUrl:require('../../assets/word/0073.png'),
    },{
        type:'1',word:'its',
        imgUrl:require('../../assets/word/0074.png'),
    },{
        type:'1',word:'our',
        imgUrl:require('../../assets/word/0075.png'),
    },
    {
        type:'1',word:'two',
        imgUrl:require('../../assets/word/0076.png'),
    },{
        type:'1',word:'more',
        imgUrl:require('../../assets/word/0077.png'),
    },{
        type:'1',word:'these',
        imgUrl:require('../../assets/word/0078.png'),
    },{
        type:'1',word:'want',
        imgUrl:require('../../assets/word/0079.png'),
    },{
        type:'1',word:'way',
        imgUrl:require('../../assets/word/0080.png'),
    },
    {
        type:'1',word:'look',
        imgUrl:require('../../assets/word/0081.png'),
    },{
        type:'1',word:'first',
        imgUrl:require('../../assets/word/0082.png'),
    },{
        type:'1',word:'also',
        imgUrl:require('../../assets/word/0083.png'),
    },{
        type:'1',word:'new',
        imgUrl:require('../../assets/word/0084.png'),
    },{
        type:'1',word:'because',
        imgUrl:require('../../assets/word/0085.png'),
    },
    {
        type:'1',word:'day',
        imgUrl:require('../../assets/word/0086.png'),
    },{
        type:'1',word:'use',
        imgUrl:require('../../assets/word/0087.png'),
    },{
        type:'1',word:'no',
        imgUrl:require('../../assets/word/0088.png'),
    },{
        type:'1',word:'man',
        imgUrl:require('../../assets/word/0089.png'),
    },{
        type:'1',word:'find',
        imgUrl:require('../../assets/word/0090.png'),
    },{
        type:'1',word:'here',
        imgUrl:require('../../assets/word/0091.png'),
    },{
        type:'1',word:'thing',
        imgUrl:require('../../assets/word/0092.png'),
    },{
        type:'1',word:'give',
        imgUrl:require('../../assets/word/0093.png'),
    },{
        type:'1',word:'many',
        imgUrl:require('../../assets/word/0094.png'),
    },{
        type:'1',word:'well',
        imgUrl:require('../../assets/word/0095.png'),
    }, 
    {
        type:'1',word:'only',
        imgUrl:require('../../assets/word/0096.png'),
    },{
        type:'1',word:'those',
        imgUrl:require('../../assets/word/0097.png'),
    },{
        type:'1',word:'tell',
        imgUrl:require('../../assets/word/0098.png'),
    },{
        type:'1',word:'very',
        imgUrl:require('../../assets/word/0099.png'),
    },{
        type:'1',word:'her',
        imgUrl:require('../../assets/word/0100.png'),
    }






]

let wordArr1 =[
    {
        type:'1',word:'even',
        imgUrl:require('../../assets/word/0101.png'),
    },{
        type:'1',word:'back',
        imgUrl:require('../../assets/word/0102.png'),
    },{
        type:'1',word:'any',
        imgUrl:require('../../assets/word/0103.png'),
    },{
        type:'1',word:'good',
        imgUrl:require('../../assets/word/0104.png'),
    },{
        type:'1',word:'women',
        imgUrl:require('../../assets/word/0105.png'),
    },{
        type:'1',word:'through',
        imgUrl:require('../../assets/word/0106.png'),
    },{
        type:'1',word:'us',
        imgUrl:require('../../assets/word/0107.png'),
    },{
        type:'1',word:'life',
        imgUrl:require('../../assets/word/0108.png'),
    },{
        type:'1',word:'child',
        imgUrl:require('../../assets/word/0109.png'),
    },{
        type:'1',word:'there',
        imgUrl:require('../../assets/word/0110.png'),
    },
]
    

export {
    wordArr ,wordArr1
}